# General
name                  : 'esra'
surname               : 'altintas'
fullname              : 'esraltintas'
fullname_human        : 'Esra Altintas'
domain                : 'http://esra.dev'

# Open Graph
og_image              : 'general/og_image_default.png'

# Paths
paths                 : 
  images              : '/assets/images/'

# Info
description           : "Esra Altıntaş'ın kişisel web sitesi."
keywords              : 'javascript, ecmascript, es6'

# System
timezone              : 'Europe/Istanbul'
include               : ['_pages']

# Filtering Content
show_drafts           : null
limit_posts           : 0

# Conversion
markdown              : kramdown
excerpt_separator     : <!--more-->

# Outputting
baseurl               : ''
permalink             : :title.html

# Sass
sass                  :
  style               : :compressed

# Scopes
defaults:
  - 
    scope             :
      path            : ''
      type            : 'pages'
    values            :
      layout          : 'page'
  -
    scope            :
      path            : ''
      type            : 'posts'
    values            :
      layout          : 'post'

  -
    scope            :
      path            : ''
      type            : 'drafts'
    values            :
      layout          : 'post'