# General
name: "esra"
surname: "aydemir"
fullname: "esraaydemir"
fullname_human: "Esra Aydemir"
domain: "http://esra.dev"

# Info
description: "Esra Aydemir'in kişisel web sitesi."
keywords: "javascript, ecmascript, es6"

# System
timezone: "Europe/Istanbul"
include: ["_pages"]

# Filtering Content
show_drafts: null
limit_posts: 0

# Conversion
markdown: kramdown
excerpt_separator: <!--more-->

# Outputting
baseurl: ""
permalink: :title.html

# Sass
sass:
  style: :compressed

# Scopes
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
